baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = "hugo-theme-relearn"
defaultContentLanguage = "ru"

[outputs]
home = [ "HTML", "RSS", "JSON"]

[params]
themeVariant = ["keepers-dark", "keepers-light"]
