baseURL = 'https://keepers.tech/'
languageCode = 'en-us'
title = 'Keepers-Team'
theme = "hugo-theme-relearn"
defaultContentLanguage = "ru"

[outputs]
home = [ "HTML", "RSS", "JSON" ]

[params]
themeVariant = ["keepers-dark", "keepers-light"]
additionalContentLanguage = [ "en" ]

[Languages]
[Languages.ru]
landingPageName = "<i class='fas fa-home'></i> Главная"
